apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - name: port-nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  nginx.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-service:80;
        }
    }